#! /usr/bin/env node

var MongoClient = require('mongodb').MongoClient
var assert = require('assert')
var dotenv = require('dotenv')

var path = require('path')
var fs = require('fs')

/**
 * Load environment variables from .env file, where API keys and passwords are configured.
 *
 * Default path: .env
 */
require('../src/dotenv.js')()

// Connection URL
var url = process.env.MONGODB

// Use connect method to connect to the Server
MongoClient.connect(url, function (err, db) {
  assert.equal(null, err)
  console.log('Connected correctly to server', url)
  db.dropDatabase()
  console.log('Dropped database successfully', url)
  db.close()
})
